replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2017-latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 1433

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: db.o2bus.com
      paths: 
       - path: /
         pathType: ImplementationSpecific
  tls: []
  #  - secretName: tls-secret-db-o2bus
  #    hosts:
  #     - db.o2bus.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
