apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-staging
spec:
  selector:
    matchLabels:
      app: nginx-staging
  template:
    metadata:
      labels:
        app: nginx-staging
    spec:
      containers:
      - image: nginx
        name: nginx-staging
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-staging-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-staging
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - nginx.staging.o2bus.com
    secretName: tls-secret
  rules:
  - host: nginx.staging.o2bus.com
    http:
      paths:
      - backend:
          service:
                name: nginx-staging-svc
                port:
                  number: 80
          # serviceName: nginx-svc
          # servicePort: 80
        path: /
        pathType: ImplementationSpecific