version: '3.4'

services:
  pfrcentr.app.mvcclient:
    image: ${DOCKER_REGISTRY-}pfrcentrapp
    build:
      context: .
      dockerfile: src/IdPortal.App.MvcClient/Dockerfile

  idportal.app.mvcclient:
    image: ${DOCKER_REGISTRY-}idportalapp
    build:
      context: .
      dockerfile: src/IdPortal.App.MvcClient/Dockerfile

