apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql-data.fullname" . }}
  labels:
    {{- include "mssql-data.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1433
      protocol: TCP
      # name: tcp
  selector:
    {{- include "mssql-data.selectorLabels" . | nindent 4 }}
