version: '3.7'

networks:
  frontend:
  backend:

services:
  sql.data:
    environment:
      - SA_PASSWORD=your@Password
      - ACCEPT_EULA=Y
      # - MSSQL_PID=Developer
    ports:
      - "5433:1433"
    networks:
      - backend

  rabbitmq:
    hostname: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 


  o2nextgen.auth.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Initial Catalog=O2NextGen.AuthDb;Persist Security Info=False;User ID=sa;Password=your@Password;Connection Timeout=30;
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5001:80"
      # - "10001:443"
    #volumes:
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sql.data
    networks:
      - backend

  o2nextgen.certificatemanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Initial Catalog=O2NextGen.CGenDb;Persist Security Info=False;User ID=sa;Password=your@Password;Connection Timeout=30;
      #- Serilog__Enrich=FromLogContext
      #- Serilog__WriteTo__Name=Console
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5002:80"
    depends_on:
      - sql.data
    networks:
      - backend
      # - "10002:443"
    #volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  o2nextgen.smalltalk.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Urls__IdentityUrl=http://o2nextgen.auth.web
      - Urls__SmallTalkSignalRUrl=http://o2nextgen.smalltalk.signalr
      - Urls__Rabbitmq=rabbitmq://rabbitmq
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5003:80"
    depends_on:
      - rabbitmq
      - o2nextgen.smalltalk.signalr
      - o2nextgen.auth.web
    networks:
      - backend
      - frontend 
      # - "10003:443"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  o2nextgen.smalltalk.signalr:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80l
      - Urls__IdentityUrl=http://o2nextgen.auth.web
      - Urls__Rabbitmq=rabbitmq://rabbitmq
      - Urls__SmallTalkUrl=http://o2nextgen.smalltalk.api 
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5103:80"
    depends_on:
      - rabbitmq
      - o2nextgen.auth.web
    networks:
      - backend
      - frontend
    
  o2nextgen.esender.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Initial Catalog=O2NextGen.ESenderDb;Persist Security Info=False;User ID=sa;Password=your@Password;Connection Timeout=30;
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5004:80"
    depends_on:
      - sql.data
    networks:
      - backend
      # - "10004:443"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  o2nextgen.mediabasket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Initial Catalog=O2NextGen.MediaBasketDb;Persist Security Info=False;User ID=sa;Password=your@Password;Connection Timeout=30;
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - CloudinarySettings__CloudName=cloudName
      - CloudinarySettings__ApiKey=api_key
      - CloudinarySettings__ApiSecret=api_secret
    ports:
      - "5005:80"
    depends_on:
      - sql.data
    networks:
      - backend

  smalltalk.app: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - Urls__IdentityUrl=http://docker.for.mac.localhost:5001
      # - Urls__SignalRUrl=http://docker.for.mac.localhost:5103
    ports:
      - "3003:80"
    depends_on:
      - o2nextgen.auth.web
      - o2nextgen.smalltalk.api
      - o2nextgen.smalltalk.signalr
    networks:
      - backend
      - frontend
  
  smalltalk.app.chat: 
    ports:
      - "3002:80"
    depends_on:
      - o2nextgen.auth.web
      - o2nextgen.smalltalk.api
      - o2nextgen.smalltalk.signalr
    networks:
      - backend
      - frontend

  o2nextgen.pfrcenterapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    depends_on:
      - o2nextgen.auth.web
    networks:
      - backend
      - frontend

