version: '3.4'
networks:
  frontend:
  backend:

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqldatacontainer
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      # - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - backend
  
  certificate.api:
    image: ${DOCKER_REGISTRY:-o2nextgen}/cgen.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./Services/c-gen/O2NextGen.CertificateManagement.Api/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${O2_AZURE_IDENTITY_DB:-Server=sql.data;Database=O2Bionics.o2nextgen.CertificateDb;User Id=sa;Password=Pass@word;}
    depends_on:
      - sql.data
    ports:
      - "10102:80"
    networks:
      - backend
      - frontend
      - frontend
