name: .NET

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Services/c-gen
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Services/c-gen
    - name: Integration Tests
      run: dotnet test IntegrationTests.O2NextGen.CertificateManagement.Api.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
      working-directory: src/Services/c-gen/Tests/IntegrationTests.O2NextGen.CertificateManagement.Api/

    - name: check files 1 
      run: ls
      working-directory: src/Services/c-gen/Tests/IntegrationTests.O2NextGen.CertificateManagement.Api/
    
    - name: check files 2 
      run: ls
      working-directory: src/Services/c-gen/Tests/IntegrationTests.O2NextGen.CertificateManagement.Api/TestResults/

    - name: check files 2 
      run: ls
      working-directory: src/Services/c-gen/Tests/

    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: src/Services/c-gen/Tests/IntegrationTests.O2NextGen.CertificateManagement.Api/TestResults/coverage.info