name: e-sender

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 2.2.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.x
    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Services/e-sender
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Services/e-sender
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/Services/e-sender
