name: o2-auth

on:
  pull_request:
    branches:
    - master
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Services/auth
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Services/auth
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/Services/auth
