// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O2NextGen.CertificateManagement.Infrastructure.Data;

#nullable disable

namespace O2NextGen.CertificateManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CertificateManagementDbContext))]
    [Migration("20221225101744_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("category_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("certificate_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("languageInfo_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("O2NextGen.CertificateManagement.Domain.Entities.CategoryDbEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "category_hilo");

                    b.Property<long>("AddedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategorySeries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeletedDate")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ModifiedDate")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantityCertificates")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPublishCode")
                        .HasColumnType("int");

                    b.Property<int>("TimeLifeInDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("O2NextGen.CertificateManagement.Domain.Entities.CertificateDbEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "certificate_hilo");

                    b.Property<long>("AddedDate")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeletedDate")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpiredDate")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<bool>("Lock")
                        .HasColumnType("bit");

                    b.Property<string>("LockInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LockedDate")
                        .HasColumnType("bigint");

                    b.Property<long>("ModifiedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PublishDate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Certificate", (string)null);
                });

            modelBuilder.Entity("O2NextGen.CertificateManagement.Domain.Entities.LanguageInfoDbEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "languageInfo_hilo");

                    b.Property<long>("AddedDate")
                        .HasColumnType("bigint");

                    b.Property<long>("CertificateId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middlename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ModifiedDate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("LanguageInfos", (string)null);
                });

            modelBuilder.Entity("O2NextGen.CertificateManagement.Domain.Entities.CertificateDbEntity", b =>
                {
                    b.HasOne("O2NextGen.CertificateManagement.Domain.Entities.CategoryDbEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("O2NextGen.CertificateManagement.Domain.Entities.LanguageInfoDbEntity", b =>
                {
                    b.HasOne("O2NextGen.CertificateManagement.Domain.Entities.CertificateDbEntity", "Certificate")
                        .WithMany("LanguageInfos")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("O2NextGen.CertificateManagement.Domain.Entities.CertificateDbEntity", b =>
                {
                    b.Navigation("LanguageInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
