name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Services/c-gen
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Services/c-gen
    - name: Integration Tests
      run: dotnet test --no-build --verbosity normal /p:CoverletOutput=../../coverlet/FooBar.Tests.json
      working-directory: src/Services/c-gen/Tests/IntegrationTests.O2NextGen.CertificateManagement.Api
